name: Build and deploy Python app to Azure Web App - excelappdeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Navigate to Backend and Set Up Virtual Environment
        run: |
          cd MyReactApp/backend
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          cd MyReactApp/backend
          pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: |
          cd MyReactApp/backend
          zip -r ../../release.zip ./*

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d backend

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5CD335A1E0D14F6EBB36469A256DD3B4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0C5F46C96D194C21BF62F49B09C1E7C0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_ED0F23C4D840424983411AAEEE0C6F8A }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'excelappdeployment'
          slot-name: 'Production'
          package: backend
